services:
  nagiyu:
    build:
      context: ./nagiyu
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}_web"
    ports:
      - "9019:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./nagiyu/bin:/app
      - ./nagiyu/fullchain.pem:/etc/letsencrypt/fullchain.pem
      - ./nagiyu/privkey.pem:/etc/letsencrypt/privkey.pem

  localstack:
    build:
      context: ./aws
      dockerfile: Dockerfile
    container_name: "${PROJECT_NAME}_localstack"
    ports:
      - "9020:4566" # LocalStackのメインエンドポイント
    environment:
      - SERVICES=kms,dynamodb
      - DEBUG=1               # デバッグログをON
